name: tests

on: [push, pull_request]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - otp: '21.3'
            elixir: '1.11'
          - otp: '26.0'
            elixir: '1.15'
          - otp: '27.0'
            elixir: '1.17'
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1
        with:
         otp-version: ${{ matrix.otp }}
         elixir-version: ${{ matrix.elixir }}
      - uses: step-security/runs-on-cache@c5b0cba15d05488ebc630ad8d1e95b3d9b35ac73 # v5.0.7
        with:
         path: deps
         key: ${{ runner.os }}-${{ matrix.elixir }}-otp${{ matrix.otp }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
         restore-keys: |
           ${{ runner.os }}-${{ matrix.elixir }}-otp${{ matrix.otp }}-mix-
      - run: mix deps.get
      - run: mix coveralls.github
